#!/bin/bash
set -eux


#via https://github.com/manics/omero-server-jupyter/blob/master/initialise.sh h/t @betatim
#Start PostgreSQL


#BORKED - it looks like we need to run:
#chown jovyan /run/postgresql/

PGDATA=${PGDATA:-/home/jovyan/srv/pgsql}

if [ ! -d "$PGDATA" ]; then
  /usr/lib/postgresql/10/bin/initdb -D "$PGDATA" --auth-host=md5 --encoding=UTF8
fi
/usr/lib/postgresql/10/bin/pg_ctl -D "$PGDATA" status || nohup /usr/lib/postgresql/10/bin/pg_ctl -D "$PGDATA" -l "$PGDATA/pg.log" start  > /dev/null 2>&1 &

psql postgres -c "CREATE USER test PASSWORD 'testpass'"
createdb -O test test

#nohup /usr/lib/postgresql/10/bin/pg_ctl -D /var/lib/postgresql/10/main -l logfile start  > /dev/null 2>&1 &

#Do the normal Binder start thing here...
exec "$@"
