#!/bin/bash
set -eux
PGDATA=${PGDATA:-/home/jovyan/srv/pgsql}
if [ ! -d "$PGDATA" ]; then
  initdb -D "$PGDATA" --auth-host=md5 --encoding=UTF8
fi

pg_ctl -D "$PGDATA" -l "$PGDATA/pg.log" start

chmod +x $HOME/init_db.sh
$HOME/init_db.sh
#Put an equivalent of the above in a config file: init_db.sql
#psql -U postgres postgres -f init_db.sql
#psql test < seed_db.sql


#Franchise
#https://github.com/HVF/franchise/blob/master/DEPLOYING_LOCALLY.md
git clone --depth 1 https://github.com/HVF/franchise.git
cd franchise
yarn install
yarn build

mkdir -p $HOME/.jupyter/

#This script runs in $HOME rather than $HOME/binder
mv jupyter_notebook_config.py $HOME/.jupyter/
