#!/bin/bash
set -eux
USER_PATH=/srv/conda

PGDATA=${PGDATA:-$USER_PATH/pgsql}
if [ ! -d "$PGDATA" ]; then
  initdb -D "$PGDATA" --auth-host=md5 --encoding=UTF8
fi

pg_ctl -D "$PGDATA" -l "$PGDATA/pg.log" start

#Copy the initialisation files into the final container
mv init_db $USER_PATH/
chmod +x $USER_PATH/init_db/postgres/init_db.sh
$USER_PATH/init_db/postgres/init_db.sh

#Put an equivalent of the above in a config file: init_db.sql
#psql -U postgres postgres -f init_db.sql
#psql test < seed_db.sql
