#!/bin/bash
set -eux

#In order to autostart the postgres server, uncomment the following two lines
#PGDATA=${PGDATA:-/home/jovyan/srv/pgsql}
#pg_ctl -D "$PGDATA" -l "$PGDATA/pg.log" start

#DEPRECATED - We get a permission error on this?
#python /srv/conda/lib/python3.6/site-packages/pgadmin4/pgAdmin4.py

exec "$@"
